import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { FileText, AlertTriangle } from "lucide-react";

export function TermsOfUse() {
  return (
    <div className="max-w-3xl mx-auto space-y-6 animate-in fade-in">
      <div className="flex items-center gap-3">
        <FileText className="h-10 w-10 text-slate-600" />
        <div>
          <h1 className="text-3xl font-bold text-slate-900">Terms of Use</h1>
          <p className="text-slate-500 text-sm">Last updated: February 2025</p>
        </div>
      </div>

      <Card className="shadow-sm border-amber-200 bg-amber-50/50">
        <CardHeader>
          <CardTitle className="text-lg flex items-center gap-2 text-amber-900">
            <AlertTriangle className="h-5 w-5" />
            Important disclaimer
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-amber-900 text-sm leading-relaxed">
          <p className="font-medium">
            The suggestions, classifications, and any other output generated by the AI Compliance Consultant chatbot are <strong>not legal advice</strong>. They are for informational and exploratory purposes only and should be treated as <strong>speculation or preliminary guidance</strong>, not as a substitute for advice from a qualified legal or compliance professional.
          </p>
          <p>
            You should consult a qualified lawyer or compliance expert before making any decisions based on the chatbot’s responses. We do not guarantee the accuracy, completeness, or suitability of the chatbot’s output for your specific situation.
          </p>
        </CardContent>
      </Card>

      <Card className="shadow-sm">
        <CardHeader>
          <CardTitle className="text-lg">1. Acceptance of Terms</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-slate-700 text-sm leading-relaxed">
          <p>
            By accessing or using EUActAudit (“Service”), you agree to these Terms of Use. If you do not agree, do not use the Service.
          </p>
        </CardContent>
      </Card>

      <Card className="shadow-sm">
        <CardHeader>
          <CardTitle className="text-lg">2. Nature of the Service</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-slate-700 text-sm leading-relaxed">
          <p>
            The Service provides AI-assisted compliance assessment and audit tools (including chat-based guidance and report generation). All such output is <strong>not legal advice</strong> and is provided on an “as is” basis for informational and speculative use only. You are responsible for obtaining appropriate professional advice before relying on any output.
          </p>
        </CardContent>
      </Card>

      <Card className="shadow-sm">
        <CardHeader>
          <CardTitle className="text-lg">3. Use of the Service</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-slate-700 text-sm leading-relaxed">
          <p>You agree to use the Service only for lawful purposes and in accordance with these terms. You must not use the Service in any way that could harm us, other users, or third parties, or that could violate applicable laws.</p>
        </CardContent>
      </Card>

      <Card className="shadow-sm">
        <CardHeader>
          <CardTitle className="text-lg">4. Disclaimer of Warranties</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-slate-700 text-sm leading-relaxed">
          <p>
            The Service and all content and output (including chatbot responses and reports) are provided “as is” and “as available” without warranties of any kind. We disclaim all warranties, express or implied, including accuracy, fitness for a particular purpose, and non-infringement. Use of the Service and reliance on any output is at your sole risk.
          </p>
        </CardContent>
      </Card>

      <Card className="shadow-sm">
        <CardHeader>
          <CardTitle className="text-lg">5. Limitation of Liability</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-slate-700 text-sm leading-relaxed">
          <p>
            To the maximum extent permitted by law, we are not liable for any indirect, incidental, special, consequential, or punitive damages, or for any loss of data, revenue, or profits, arising from your use of the Service or reliance on any chatbot output or generated reports.
          </p>
        </CardContent>
      </Card>

      <Card className="shadow-sm">
        <CardHeader>
          <CardTitle className="text-lg">6. Changes and Contact</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-slate-700 text-sm leading-relaxed">
          <p>
            We may update these Terms of Use at any time. The “Last updated” date reflects the latest version. Continued use of the Service after changes constitutes acceptance. For questions about these terms, please contact us through the channels provided in the app or website.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
